### PR TITLE
Add option --use-openssh-config to use connection parameters from the…

### PR DESCRIPTION
**Pull request by supercoolin**
This pull request adds an option to use ssh jumps specified within a openssh config file located at $HOME/.ssh/config. To use this option you must also use the --no-conntest  option for now.

### CODE REVIEW

**Comment by tbarbette** [comment]
Could you make it so it works with no-conntest?
Also is there a reason to not make this the default? And invert the option like --no-ssh-config
Finaly it would be great if you made it an optional argument where a specific path can be given, and if it's not given just use $USER/.ssh/config ?

**Comment by tbarbette** [comment]
Sorry I had left this PR in my pile

**Comment by tbarbette** [comment]
Where are we on this?

**Comment by supercoolin** [comment]
Basically I need to rethink about the moment during which I do the parsing in the npf-lifecycle. I need to know the host addresses before the connection test.

**Pull request closed without merging**
