### PR TITLE
Pandas support

### PR DESCRIPTION
**Pull request by aliireza**
This patch will make a Pandas dataframe from all_results and print it in a CSV format, which can be loaded later for post-processing.

I tried with the following testie file and it worked:

%config
n_runs=2

%variables
NUMBER_1=[5-8]
NUMBER_2=[1-5]
NUMBER_3=[20-22]
test={hi,bye}

%script
ADD=$(echo "$NUMBER_1 + $NUMBER_2" | bc)
MULT=$(echo "$NUMBER_1 * $NUMBER_2" | bc)
echo "RESULT-ADDITION $ADD"
echo "RESULT-MULT $MULT"

### CODE REVIEW

**Comment by tbarbette** [comment]
It would be great to add a runtime flag to enable it, such as "--panda [path]"

**Comment by aliireza** [comment]
I am checking it now with [ddio-bench](https://github.com/aliireza/ddio-bench). 

If it works, I will add the flag ;)

**Comment by aliireza** [comment]
I updated the README for `--pandas` and added one example to process it.

**Comment by tbarbette** [comment]
Great, thanks!
I'll merge in like this, but I think the file will get overwritten fi there are multiple series. We can fix that later though.

**Comment by aliireza** [comment]
Thanks :) 
I think they will be added to the data frame as long as different series have different build tag. Otherwise, we cannot really distinguish them. We can fix it later if you notice something.

**Pull request merged**
